version: '3'
services:
  rspec:
    build: .
    command: rspec
    volumes:
      - .:/app
    depends_on:
      - bundle_install
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - migration
      - bundle_install
  migration:
    build: .
    command: rails db:migrate RAILS_ENV=development
    volumes:
      - .:/app
  bundle_install:
    build: .
    command: bundle install
    volumes:
      - .:/app
