version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - migration
  migration:
    build: .
    command: rails db:migrate RAILS_ENV=development
    volumes:
      - .:/app
